### ISSUE TITLE
Apply strategy for inner traversals

### ISSUE THREAD

**Issue by eliranmoyal** [rmagen/elastic-gremlin#21]
on RepeatStep , MatchStep, UnionStep and maby more
the inner traversal does not work with out stratagy - mostly because it does not start with GraphStep.
need to fix it to make it more efficent

**Comment by rmagen** [comment]
isn't this complete with 20713c2b32e319d0f628deb805f2439dadc56821 ?

**Comment by eliranmoyal** [comment]
match is not fully completed (but I think i'll stop working on it) .
Union and repeat working very good now.
haven't search for other steps influenced from what i did (maybe they got worse on performance) , but all the tests passed. 
So it partially closed, i'll create a pull request with what i did.

**Comment by rmagen** [comment]
For now I disabled optimizations on inner traversals. Working on getting it working back again.

**Comment by rmagen** [comment]
Waiting on https://issues.apache.org/jira/browse/TINKERPOP3-702

**Comment by rmagen** [comment]
implemented with the new queryHandler
