### ISSUE TITLE
avoid using ElasticEdge.vertexIterator()

### ISSUE THREAD

**Issue by rmagen** [rmagen/elastic-gremlin#27]
vertexIterator is called many times in the following situations, opting many unnecessary queries from the db:
1. elasticEdge.toString()
2. GraphsonSerealizer, when serializing edges

**Comment by eliranmoyal** [comment]
1. fixed the toString.
052eb367ff6e3ea622155c55f243dbf129caa24a
2 : i saw configuration on gremlinServer
what about inhering the Serializer override the json implementation of Edge and referencing our own class?

**Comment by rmagen** [comment]
that might be possible, but i prefer checking first how vertexIterator is implemented in other TP implementations, since they don't seem to suffer from this issue.

**Comment by rmagen** [comment]
another possible solution is utilizing the lazy loading we will implement in #23.
since vertexIterator will just create a lazy reference to the vertex, using it in these use-cases won't incur an extra query. 
but this  requires that the lazy vertex contain a label as well, which means we need to store the in and out labels in the edge's document.

**Comment by eliranmoyal** [comment]
+1

*g.E().outV('some_label')

**Comment by rmagen** [comment]
@eliranmoyal, check out 'lazy' branch..
I still haven't added usage of lazy vertices in traversals. I'll do it soon.
Also, so far I haven't found a good reason to do lazy edges.
