### ISSUE TITLE
Add documentation for elastic-gremlin configurations

### ISSUE THREAD

**Issue by rmagen** [rmagen/elastic-gremlin#33]
* batch
* refresh
* cluster name
* client type
* upsert
* SchemaProvider
  * DefaultSchemaProvider
  * Tips for creating your own optimized indices

**Comment by eliranmoyal** [comment]
@rmagen check what i've added on the readme file

**Comment by rmagen** [comment]
very good :)
I'll make a few more changes before we close this issue.
also, we need to update the Server and Client instructions to make it compatible with M8

**Comment by rmagen** [comment]
Also, refresh happens before searching, not after inserting.
So it also doesn't interfere with bulk loading.
