### ISSUE TITLE
Profile all querying

### ISSUE THREAD

**Issue by Lande24** [rmagen/elastic-gremlin#63]
We need to count the number of queries we issue to the backend in order to make sure the bulking mechanism works correctly. We should also measure the duration of the queries to make sure everything works as expected.
This could either be implemented using the TimingAccessor, or alternatively using the Profiling interface which the traversal steps implement.

**Comment by rmagen** [comment]
Good work. You should probably finish it off by passing the Timer to ElasticMutations as well and timing the mutations. can't hurt..
